name: smartcmms-backend
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # for testing purposes
    networks:
      - backend
  db-log:
    image: mongodb/mongodb-community-server
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - db-log_data:/data/db
    ports:
      - 27017:27017 # for testing purposes
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - backend
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: db-log
    ports:
      - 8089:8081
    networks:
      - backend
    links:
      - "db-log:mongo"
  backend:
    image: smartcmms-backend:latest
    restart: always
    ports:
      - 5000:5000
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      EMAIL_EMAIL: ${EMAIL_EMAIL}
      EMAIL_TOKEN: ${EMAIL_TOKEN}
      IN_DOCKER_CONTAINER: "1"
    networks:
      - frontend
      - backend
  frontend:
    image: smartcmms-frontend:latest
    restart: always
    environment:
      VITE_BACKEND_URL: ${BACKEND_URL}
    ports:
      - 5001:3000
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db_data:
  db-log_data:
