name: smartcmms-backend
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  backend:
    image: smartcmms-backend:latest
