name: Build and run backend

on:
  push:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build backend
        run: |
          docker build -t smartcmms-backend . -f backend/Dockerfile --target build
  build-frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build frontend
        run: |
          docker build -t smartcmms-frontend . -f frontend/Dockerfile

  run:
    runs-on: self-hosted
    needs:
      - build-backend
      - build-frontend
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "MONGO_USER=${{ secrets.MONGO_USER }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
      - name: Run docker compose
        run: |
          docker compose down
          docker compose up --detach
